### ISSUE TITLE
Installation instructions unclear

### ISSUE THREAD

**Issue by ts-web** [JamieMason/karma-jasmine-matchers#3] opened 2014-09-23 17:50 UTC
After running `bower install jasmine-expect --save-dev` and adding `jasmine-matchers` to my karma config file's frameworks array, it does not work.

I run `grunt karma` and I get the error:

    Warning: No provider for "framework:jasmine-matchers"! (Resolving: framework:jasmine-matchers) Use --force to continue.

What installation step am I missing?

**Comment by JamieMason** [comment] 2015-02-24 08:23
Thanks all for your help, but closing as like @ts-web, I can't reproduce the error.

**Closed by JamieMason** 2015-02-24 08:23 UTC
Labels: help wanted

**Comment by antenko** [comment] 2015-10-22 09:12
@ts-web @JamieMason Hi!
I had the same issue today. 
I had globally installed Karma and local ./node_modules/karma-jasmine-matchers . So when I was starting something like this `karma start test/karma.conf.js` I started global karma which know nothing about my local matchers.
So if you'll use local karma and local matchers or install matchers globally you'll fix your problem.
Good Luck!

P.S. Sorry for my English :)

**Comment by JamieMason** [comment] 2015-10-23 09:26
Thanks a lot @antenko I'll remember to add this to the README.

**Comment by mwpeng** [comment] 2015-10-28 03:01
@JamieMason 
I think this is about the default value of plugins config

Karma has a default value for [plugins](http://karma-runner.github.io/0.13/config/plugins.html):
```javascript
plugins: ['karma-*']
```

That's to say 'karma-jasmine-matchers' is actually need to be listed in pulgins array.

In a project that the default pulgins config is overwritten,  'karma-jasmine-matchers'  should be listed explicitly in pulgins config.

If you add
```javascript
plugins: ['karma-jasmine']
```
 to  karma.conf.js, [my fork of example project](https://github.com/mwpeng/karma-jasmine-matchers):

This error will occur, since jasmine-matchers is not loaded as a plugin.
```
Error: No provider for "framework:jasmine-matchers"! (Resolving: framework:jasmine-matchers)
```


Hope this helps.
